---
# Service deployment targets
base_setup_service_deploy_targets:
  - user: nextcloud
    home: /var/services/nextcloud
    containers_dir: ../service-nextcloud/containers
    volumes_dir: ../service-nextcloud/volumes
    networks_dir: ../service-nextcloud/networks
  - user: proxy
    home: /var/services/proxy
    containers_dir: ../service-bunker/containers
    volumes_dir: ../service-bunker/volumes
    networks_dir: ../service-bunker/networks

# Shared network file (deployed to both users)
base_setup_shared_network_source: ../service-nextcloud/networks/shared-network.network

# Nextcloud configs to deploy
base_setup_nextcloud_configs:
  - user: nextcloud
    home: /var/services/nextcloud
    src: ../service-nextcloud/containers/configs/nginx.conf
    dst: configs/nginx.conf
  - user: nextcloud
    home: /var/services/nextcloud
    src: ../service-nextcloud/containers/context/configs/php-config.ini
    dst: context/configs/php-config.ini
  - user: nextcloud
    home: /var/services/nextcloud
    src: ../service-nextcloud/containers/context/configs/prev.config.php
    dst: context/configs/prev.config.php
  - user: nextcloud
    home: /var/services/nextcloud
    src: ../service-nextcloud/containers/context/configs/phone.config.php
    dst: context/configs/phone.config.php
  - user: nextcloud
    home: /var/services/nextcloud
    src: ../service-nextcloud/containers/context/configs/log.config.php
    dst: context/configs/log.config.php
