---
# SecureBlue Deployment Playbook

- name: Base system setup (Btrfs, Users, SELinux, Snapshots)
  hosts: all
  gather_facts: true
  roles:
    - base_setup

- name: Deploy Nextcloud service
  hosts: all
  gather_facts: false
  roles:
    - role: nextcloud_service
      vars:
        nextcloud_service_user: nextcloud
        nextcloud_service_home: /var/services/nextcloud

- name: Deploy Bunkerweb service
  hosts: all
  gather_facts: false
  roles:
    - role: bunker_service
      vars:
        bunker_service_user: proxy
        bunker_service_home: /var/services/proxy
