---
- name: Restart snapshot services
  ansible.builtin.systemd:
    name: "btrfs-snapshot@{{ item }}"
    state: restarted
  loop:
    - nextcloud
    - proxy
    - monitoring

- name: Apply sysctl setting
  ansible.builtin.command: sysctl -w net.ipv4.ip_unprivileged_port_start=80
  changed_when: true
