---
- name: Apply sysctl setting
  ansible.builtin.command: sysctl -w net.ipv4.ip_unprivileged_port_start=80
  changed_when: true

- name: Start zram swap
  ansible.builtin.systemd:
    name: systemd-zram-setup@zram0.service
    state: started
    daemon_reload: true

- name: Restart iscsid
  ansible.builtin.systemd:
    name: iscsid.service
    state: restarted

- name: Reload systemd for crypttab
  ansible.builtin.systemd:
    daemon_reload: true

- name: Apply EEE now
  ansible.builtin.command: /etc/NetworkManager/dispatcher.d/10-eee-off {{ item }} up
  loop: "{{ base_setup_eee_off }}"
  changed_when: true
